# no need for sudo and use the container based infrastructure
sudo: false
# remember maven cache (only available with the above switch)
cache:
  directories:
  - $HOME/.m2
language:
    java
jdk:
    - openjdk6
script:
    mvn clean verify